# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/cnniot/cnniot.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cnniot || ORIG_REF_NAME==cnniot} -quiet] -quiet

# IP: bd/cnniot/ip/cnniot_cnn_0_0/cnniot_cnn_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cnniot_cnn_0_0 || ORIG_REF_NAME==cnniot_cnn_0_0} -quiet] -quiet

# IP: bd/cnniot/ip/cnniot_processing_system7_0_0/cnniot_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cnniot_processing_system7_0_0 || ORIG_REF_NAME==cnniot_processing_system7_0_0} -quiet] -quiet

# IP: bd/cnniot/ip/cnniot_axi_dma_0_0/cnniot_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cnniot_axi_dma_0_0 || ORIG_REF_NAME==cnniot_axi_dma_0_0} -quiet] -quiet

# IP: bd/cnniot/ip/cnniot_proc_sys_reset_0_0/cnniot_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cnniot_proc_sys_reset_0_0 || ORIG_REF_NAME==cnniot_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/cnniot/ip/cnniot_axi_interconnect_0_0/cnniot_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cnniot_axi_interconnect_0_0 || ORIG_REF_NAME==cnniot_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/cnniot/ip/cnniot_smartconnect_0_0/cnniot_smartconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cnniot_smartconnect_0_0 || ORIG_REF_NAME==cnniot_smartconnect_0_0} -quiet] -quiet

# IP: bd/cnniot/ip/cnniot_auto_pc_0/cnniot_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==cnniot_auto_pc_0 || ORIG_REF_NAME==cnniot_auto_pc_0} -quiet] -quiet

# XDC: bd/cnniot/cnniot_ooc.xdc
