# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/FPGA_src/github_lab/GitHub_CNNIOT/repro_cnniot/cnniot_vivado/cnniot/cnniot.srcs/sources_1/bd/cnniot/ip/cnniot_proc_sys_reset_0_0/cnniot_proc_sys_reset_0_0.xci
# IP: The module: 'cnniot_proc_sys_reset_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FPGA_src/github_lab/GitHub_CNNIOT/repro_cnniot/cnniot_vivado/cnniot/cnniot.srcs/sources_1/bd/cnniot/ip/cnniot_proc_sys_reset_0_0/cnniot_proc_sys_reset_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'cnniot_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/FPGA_src/github_lab/GitHub_CNNIOT/repro_cnniot/cnniot_vivado/cnniot/cnniot.srcs/sources_1/bd/cnniot/ip/cnniot_proc_sys_reset_0_0/cnniot_proc_sys_reset_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'cnniot_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/FPGA_src/github_lab/GitHub_CNNIOT/repro_cnniot/cnniot_vivado/cnniot/cnniot.srcs/sources_1/bd/cnniot/ip/cnniot_proc_sys_reset_0_0/cnniot_proc_sys_reset_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cnniot_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: d:/FPGA_src/github_lab/GitHub_CNNIOT/repro_cnniot/cnniot_vivado/cnniot/cnniot.srcs/sources_1/bd/cnniot/ip/cnniot_proc_sys_reset_0_0/cnniot_proc_sys_reset_0_0.xci
# IP: The module: 'cnniot_proc_sys_reset_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/FPGA_src/github_lab/GitHub_CNNIOT/repro_cnniot/cnniot_vivado/cnniot/cnniot.srcs/sources_1/bd/cnniot/ip/cnniot_proc_sys_reset_0_0/cnniot_proc_sys_reset_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'cnniot_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/FPGA_src/github_lab/GitHub_CNNIOT/repro_cnniot/cnniot_vivado/cnniot/cnniot.srcs/sources_1/bd/cnniot/ip/cnniot_proc_sys_reset_0_0/cnniot_proc_sys_reset_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'cnniot_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: d:/FPGA_src/github_lab/GitHub_CNNIOT/repro_cnniot/cnniot_vivado/cnniot/cnniot.srcs/sources_1/bd/cnniot/ip/cnniot_proc_sys_reset_0_0/cnniot_proc_sys_reset_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'cnniot_proc_sys_reset_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
